import io
from datetime import datetime, timezone
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, HRFlowable
)

def generate_investigation_pdf(
    case_data: Dict[str, Any],
    evidence_list: List[Dict[str, Any]],
    analysis_results: List[Dict[str, Any]],
    risk_profile: Dict[str, Any],
    investigator_notes: List[Dict[str, Any]],
    generated_by_user: str
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    # Custom forensic styling palette
    PRIMARY_COLOR = colors.HexColor("#0f172a")  # Dark slate
    ACCENT_CYAN = colors.HexColor("#0284c7")    # Deep cyan/blue
    BORDER_COLOR = colors.HexColor("#cbd5e1")   # Slate border
    ALERT_RED = colors.HexColor("#dc2626")
    WARNING_AMBER = colors.HexColor("#d97706")
    SAFE_GREEN = colors.HexColor("#16a34a")

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=PRIMARY_COLOR,
        spaceAfter=4
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#475569"),
        spaceAfter=12
    )

    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=ACCENT_CYAN,
        spaceBefore=14,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#1e293b")
    )

    hash_style = ParagraphStyle(
        'HashStyle',
        parent=styles['Normal'],
        fontName='Courier',
        fontSize=7,
        leading=9,
        textColor=colors.HexColor("#0f172a")
    )

    disclaimer_style = ParagraphStyle(
        'DisclaimerText',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#64748b")
    )

    elements = []

    # --- Header Banner ---
    elements.append(Paragraph("TRUSTGUARD AI — DIGITAL EVIDENCE INVESTIGATION REPORT", title_style))
    elements.append(Paragraph("AI-Assisted Cybercrime Analysis & Evidence Integrity Verification", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT_CYAN, spaceAfter=10))

    # --- Case Metadata Table ---
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    case_info_data = [
        [
            Paragraph("<b>Case Number:</b> " + case_data.get("case_number", "N/A"), body_style),
            Paragraph("<b>Generated:</b> " + now_str, body_style)
        ],
        [
            Paragraph("<b>Title:</b> " + case_data.get("title", "N/A"), body_style),
            Paragraph("<b>Complaint Category:</b> " + case_data.get("complaint_category", "N/A"), body_style)
        ],
        [
            Paragraph("<b>Priority:</b> " + str(case_data.get("priority", "N/A")).upper(), body_style),
            Paragraph("<b>Case Status:</b> " + str(case_data.get("status", "N/A")).upper(), body_style)
        ],
        [
            Paragraph("<b>Assigned Investigator:</b> " + case_data.get("assigned_investigator_name", "Unassigned"), body_style),
            Paragraph("<b>Report Generated By:</b> " + generated_by_user, body_style)
        ]
    ]

    t_meta = Table(case_info_data, colWidths=[270, 270])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ('BOX', (0, 0), (-1, -1), 1, BORDER_COLOR),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_meta)
    elements.append(Spacer(1, 10))

    # --- Executive Risk Assessment ---
    elements.append(Paragraph("1. Executive Risk Assessment", section_heading))
    risk_level = risk_profile.get("overall_risk_level", "LOW")
    risk_score = risk_profile.get("overall_risk_score", 0.0)

    risk_badge_color = (
        ALERT_RED if risk_level in ["CRITICAL", "HIGH"]
        else WARNING_AMBER if risk_level == "MEDIUM"
        else SAFE_GREEN
    )

    risk_summary_text = (
        f"<b>Synthesized Case Risk Level:</b> {risk_level} (Score: {risk_score}/100.0)<br/>"
        f"<b>Analyzed Evidence Units:</b> {risk_profile.get('analysis_count', 0)} files evaluated. "
        f"Evaluation performed utilizing rule-based heuristic correlation and multi-modal feature telemetry."
    )
    elements.append(Paragraph(risk_summary_text, body_style))
    elements.append(Spacer(1, 8))

    # --- Evidence Inventory & Chain of Custody ---
    elements.append(Paragraph("2. Evidence Inventory & Cryptographic Hash Verification", section_heading))
    elements.append(Paragraph(
        "Original evidentiary files are stored in immutable private object storage. "
        "SHA-256 cryptographic digests verify that digital items have remained unaltered since ingestion.",
        disclaimer_style
    ))
    elements.append(Spacer(1, 6))

    evidence_table_data = [
        ["Item / File Name", "Type", "Size", "SHA-256 Cryptographic Hash"]
    ]

    for item in evidence_list:
        size_kb = round(item.get("file_size", 0) / 1024, 1)
        evidence_table_data.append([
            Paragraph(item.get("original_filename", "unnamed"), body_style),
            Paragraph(item.get("evidence_type", "data").upper(), body_style),
            Paragraph(f"{size_kb} KB", body_style),
            Paragraph(item.get("sha256_hash", "N/A"), hash_style)
        ])

    if len(evidence_table_data) == 1:
        evidence_table_data.append(["No evidence registered", "-", "-", "-"])

    t_evidence = Table(evidence_table_data, colWidths=[130, 60, 50, 300])
    t_evidence.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 8),
        ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(t_evidence)
    elements.append(Spacer(1, 10))

    # --- Forensic Analysis Findings ---
    elements.append(Paragraph("3. Forensic Findings by Analyzed Component", section_heading))
    if not analysis_results:
        elements.append(Paragraph("No automated analysis jobs have been executed for this case yet.", body_style))
    else:
        for res in analysis_results:
            job_header = f"<b>{res.get('analysis_type', 'General').upper()} Analysis</b> | Model: {res.get('model_name', 'Engine')} ({res.get('model_version', '1.0')}) | Risk: {res.get('risk_level', 'N/A')} ({res.get('risk_score', 0)}/100)"
            elements.append(Paragraph(job_header, body_style))
            
            # Print findings or indicators
            findings = res.get("findings_json", {})
            if isinstance(findings, dict):
                # Check for indicators in text
                indicators = findings.get("indicators", [])
                for ind in indicators:
                    ind_desc = f"• <b>[{ind.get('severity')}] {ind.get('category')}:</b> {ind.get('description')}"
                    elements.append(Paragraph(ind_desc, body_style))
                
                # Check for audio / video notes
                note = findings.get("model_status_note")
                if note:
                    elements.append(Paragraph(f"• <i>Diagnostic Status:</i> {note}", disclaimer_style))
                
                transcription = findings.get("transcription")
                if transcription:
                    elements.append(Paragraph(f"• <i>Transcription snippet:</i> \"{transcription}\"", body_style))

            elements.append(Spacer(1, 6))

    # --- Investigator Case Notes ---
    elements.append(Paragraph("4. Investigator Notes & Observations", section_heading))
    if not investigator_notes:
        elements.append(Paragraph("No investigator notes recorded.", body_style))
    else:
        for note in investigator_notes:
            note_line = f"<b>{note.get('author_name', 'Investigator')}</b> ({note.get('created_at', '')}): {note.get('note')}"
            elements.append(Paragraph(note_line, body_style))
            elements.append(Spacer(1, 4))

    # --- Limitations & Legal Disclaimer ---
    elements.append(Spacer(1, 6))
    elements.append(Paragraph("5. Forensic Limitations & Legal Disclaimer", section_heading))
    disclaimer_block = (
        "<b>STATUTORY NOTICE & LIMITATION OF LIABILITY:</b><br/>"
        "1. This document is an automated AI-assisted preliminary investigative advisory report produced by the TrustGuard AI platform.<br/>"
        "2. The platform and its algorithms do not independently establish criminal guilt, identify suspects, or provide legally conclusive proof of fraud.<br/>"
        "3. All acoustic, visual, and textual indicators represent mathematical and heuristic anomaly scores that must be independently verified by certified forensic examiners prior to submission to any judicial or regulatory authority.<br/>"
        "4. Caller reputation data reflects unverified crowd-sourced reports and telecom formatting validation only, with zero real-time geographic tracking."
    )
    elements.append(Paragraph(disclaimer_block, disclaimer_style))
    elements.append(Spacer(1, 14))

    # --- Signature Block ---
    sig_data = [
        [
            Paragraph("<b>Investigator Signature:</b> ___________________________", body_style),
            Paragraph("<b>Digital Forensic Seal:</b> [TRUSTGUARD-VERIFIED-INTEGRITY]", body_style)
        ],
        [
            Paragraph("<b>Date of Verification:</b> ___________________________", body_style),
            Paragraph("<b>Chain of Custody Status:</b> INTACT", body_style)
        ]
    ]
    t_sig = Table(sig_data, colWidths=[270, 270])
    t_sig.setStyle(TableStyle([
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(KeepTogether(t_sig))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
